services:
  # 1. AI/ML FastAPI Microservice
  - type: web
    name: amdox-ml-service
    env: python
    plan: free
    rootDir: ml-service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.9"

  # 2. NestJS Backend Gateway
  - type: web
    name: amdox-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push --accept-data-loss && node prisma/seed.js && node dist/src/main.js
    envVars:
      - key: DATABASE_URL
        value: file:dev.db
      - key: ML_SERVICE_URL
        fromService:
          name: amdox-ml-service
          type: web
          property: host
      - key: NODE_VERSION
        value: "22.12.0"

  # 3. Next.js Frontend
  - type: web
    name: amdox-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: amdox-backend
          type: web
          property: hostport

      - key: NODE_VERSION
        value: "22.12.0"
